### ISSUE TITLE
Are Charles Mendoza? 

### ISSUE THREAD

**Issue by ZeldCalcifer123** [charlescabbage/charlescabbage.github.io#1]
Not gonna lie, I only use github for searching for open source codes that I can use and study on, I don't really use it regularly. But is this how you communicate in GitHub?

**Comment by charlescabbage** [comment]
You could contact me at any of my accounts (linkedin or stackoverfow) linked at the bottom/footer of my portfolio page (https://charlescabbage.github.io/)

**Comment by ZeldCalcifer123** [comment]
Mr. Charles, I'm a 17 year old who's really eager to learn
programming/coding in hopes to one day use it to help my family one day,
i'd like to be your apprentice by any chance.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
